version: '3'

services:
  auth:
    container_name: auth
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - BUILD_CONTEXT=auth
    ports:
      - '8080:80'
  admin:
    container_name: admin
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - BUILD_CONTEXT=admin
    ports:
      - '8082:80'
